apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-bot-api.fullname" . }}
  labels:
    {{- include "telegram-bot-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_API_ID: {{ required "telegram.apiId is required" .Values.telegram.apiId | quote }}
  TELEGRAM_API_HASH: {{ required "telegram.apiHash is required" .Values.telegram.apiHash | quote }}
